### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xfirm**
Suggestion to note the hax name.

### CODE REVIEW

**Comment by Syphurith** [comment]
@xfirm If you like you can use Markdown syntax to highlight part of it. Feel free to click the [Styling with Markdown is supported](https://guides.github.com/features/mastering-markdown/) around the comment box to learn about how to do so.

# Memchunkhax2
*Memchunkhax2* is like *Memchunkhax1* that ever used by yellows8, but it´s working on firmwares higher than 9.2. It uses the new *snshax* by smealum.

This also works one firmware 10.3 . This is a **WIP**. At the moment we don´t have working code.

**Comment by xfirm** [comment]
@Syphurith thanks, never noticed that! will use on future pull requests

**Comment by xfirm** [comment]
Closing because info not valid after re-watching the stream.

**Comment by 100pcrack** [comment]
What info isn't valid @xfirm ??

**Pull request closed without merging**
